/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_so_model_Interface */

#ifndef _Included_com_so_model_Interface
#define _Included_com_so_model_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_so_model_Interface
 * Method:    initModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_so_model_Interface_initModel
  (JNIEnv *, jclass);

/*
 * Class:     com_so_model_Interface
 * Method:    identify
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_so_model_Interface_identify
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_so_model_Interface
 * Method:    freeModel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_so_model_Interface_freeModel
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
